name: SonarQube Pipeline CI/CD Workfows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  sonarQubeScan1:
    name: sonarQubeScan1
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan 1
        uses: SonarSource/sonarqube-scan-action@v4

        env:
          SONAR_TOKEN: "a039eb77fd82f30bab37a0b974d1d30bd251dc88"
          SONAR_HOST_URL: "http://13.48.135.244:9000"
